SELECT
  COUNT(*),
  ac.AIRCRAFT_MANUFACTURER,
  ac.AIRCRAFT_MODEL,
  ROUND(AVG(r.AVERAGE_RATING), 2),
  AVG(r.SEAT_COMFORT),
  AVG(r.CABIN_STAFF_SERVICE),
  AVG(r.FOOD_AND_BEVERAGES),
  AVG(r.GROUND_SERVICE)
FROM
  BRITISH_AIRWAYS_DB.MARTS.DIM_AIRCRAFT ac
  JOIN BRITISH_AIRWAYS_DB.MARTS.FCT_REVIEW_ENRICHED r ON ac.AIRCRAFT_ID = r.AIRCRAFT_ID
WHERE
  ac.AIRCRAFT_MANUFACTURER IS NOT NULL
GROUP BY
  ac.AIRCRAFT_MANUFACTURER,
  ac.AIRCRAFT_MODEL
ORDER BY
  ac.AIRCRAFT_MODEL,
  AVG(r.AVERAGE_RATING) DESC