SELECT
  'SEAT_COMFORT' AS category,
  AVG(SEAT_COMFORT) AS avg_rating
FROM
  BRITISH_AIRWAYS_DB.MARTS.FCT_REVIEW_ENRICHED
GROUP BY
  'SEAT_COMFORT'
UNION
SELECT
  'CABIN_STAFF_SERVICE' AS category,
  AVG(CABIN_STAFF_SERVICE) AS avg_rating_staff
FROM
  BRITISH_AIRWAYS_DB.MARTS.FCT_REVIEW_ENRICHED
GROUP BY
  'CABIN_STAFF_SERVICE'
UNION
SELECT
  'FOOD_AND_BEVERAGES' AS category,
  AVG(FOOD_AND_BEVERAGES) AS avg_rating_food
FROM
  BRITISH_AIRWAYS_DB.MARTS.FCT_REVIEW_ENRICHED
GROUP BY
  'FOOD_AND_BEVERAGES'
UNION
SELECT
  'GROUND_SERVICE' AS category,
  AVG(GROUND_SERVICE) AS avg_rating_ground
FROM
  BRITISH_AIRWAYS_DB.MARTS.FCT_REVIEW_ENRICHED
GROUP BY
  'GROUND_SERVICE'
UNION
SELECT
  'INFLIGHT_ENTERTAINMENT' AS category,
  AVG(INFLIGHT_ENTERTAINMENT) AS avg_rating_entertainment
FROM
  BRITISH_AIRWAYS_DB.MARTS.FCT_REVIEW_ENRICHED
GROUP BY
  'INFLIGHT_ENTERTAINMENT'
UNION
SELECT
  'WIFI_AND_CONNECTIVITY' AS category,
  AVG(WIFI_AND_CONNECTIVITY) AS avg_rating_wifi
FROM
  BRITISH_AIRWAYS_DB.MARTS.FCT_REVIEW_ENRICHED
GROUP BY
  'WIFI_AND_CONNECTIVITY'