SELECT
  AVG(AVERAGE_RATING) AS "AVG Rating",
  lo.CITY AS "Origin City",
  ld.CITY AS "Destination City",
  COUNT(*) AS "Count"
FROM
  BRITISH_AIRWAYS_DB.MARTS.FCT_REVIEW_ENRICHED r
  JOIN BRITISH_AIRWAYS_DB.MARTS.DIM_LOCATION lo ON r.ORIGIN_LOCATION_ID = lo.LOCATION_ID
  JOIN BRITISH_AIRWAYS_DB.MARTS.DIM_LOCATION ld ON r.DESTINATION_LOCATION_ID = ld.LOCATION_ID
WHERE
  lo.CITY IN (
    SELECT
      l.CITY
    FROM
      BRITISH_AIRWAYS_DB.MARTS.FCT_REVIEW_ENRICHED r
      JOIN BRITISH_AIRWAYS_DB.MARTS.DIM_LOCATION l ON r.ORIGIN_LOCATION_ID = l.LOCATION_ID
    GROUP BY
      l.CITY
    ORDER BY
      COUNT(*) DESC
    LIMIT
      5
  )
  AND ld.CITY IN (
    SELECT
      l.CITY
    FROM
      BRITISH_AIRWAYS_DB.MARTS.FCT_REVIEW_ENRICHED r
      JOIN BRITISH_AIRWAYS_DB.MARTS.DIM_LOCATION l ON r.DESTINATION_LOCATION_ID = l.LOCATION_ID
    GROUP BY
      l.CITY
    ORDER BY
      COUNT(*) DESC
    LIMIT
      5
  )
GROUP BY
  lo.CITY,
  ld.CITY
ORDER BY
  COUNT(*) DESC
LIMIT
  5