SELECT
  CASE
    WHEN RECOMMENDED = 'true' THEN 'Yes'
    ELSE 'No'
  END AS RECOMMENDED,
  COUNT(*) AS cnt,
  ROUND(
    COUNT(*) / (
      SELECT
        COUNT(*)
      FROM
        BRITISH_AIRWAYS_DB.MARTS.FCT_REVIEW_ENRICHED
    ),
    4
  ) AS percentage
FROM
  BRITISH_AIRWAYS_DB.MARTS.FCT_REVIEW_ENRICHED
GROUP BY
  RECOMMENDED