SELECT
  CAST(YEAR(DATE_FLOWN_ID) AS TEXT) AS "Year",
  COUNT(*) AS "Total Reviews",
  ROUND(
    SUM(
      CASE
        WHEN RECOMMENDED = 'true' THEN 1
        ELSE 0
      END
    ) / COUNT(*),
    4
  ) AS "Recommendation",
  AVG(AVERAGE_RATING) AS "AVG Rating",
  AVG(SEAT_COMFORT) AS "AVG Seat Comfort",
  AVG(FOOD_AND_BEVERAGES) AS "AVG Food and Beverages",
  AVG(GROUND_SERVICE) AS "AVG Ground Service",
  AVG(VALUE_FOR_MONEY) AS "AVG Money Value",
  AVG(CABIN_STAFF_SERVICE),
  AVG(INFLIGHT_ENTERTAINMENT)
FROM
  BRITISH_AIRWAYS_DB.MARTS.FCT_REVIEW_ENRICHED
WHERE
  DATE_FLOWN_ID IS NOT NULL
GROUP BY
  YEAR(DATE_FLOWN_ID)
ORDER BY
  "Year"