SELECT
  COUNT(*),
  l.city
FROM
  BRITISH_AIRWAYS_DB.MARTS.FCT_REVIEW_ENRICHED r
  JOIN BRITISH_AIRWAYS_DB.MARTS.DIM_LOCATION l ON r.DESTINATION_LOCATION_ID = l.LOCATION_ID
GROUP BY
  l.city
ORDER BY
  COUNT(*) DESC
LIMIT
  5