SELECT
  a.AIRCRAFT_MODEL,
  COUNT(*)
FROM
  BRITISH_AIRWAYS_DB.MARTS.FCT_REVIEW_ENRICHED r
  JOIN BRITISH_AIRWAYS_DB.MARTS.DIM_AIRCRAFT a ON r.AIRCRAFT_ID = a.AIRCRAFT_ID
GROUP BY
  a.AIRCRAFT_MODEL
ORDER BY
  COUNT(*) DESC
LIMIT
  6