SELECT
  COUNT(*),
  e.TRANSIT_LOCATION_ID,
  l.AIRPORT,
  l.CITY
FROM
  BRITISH_AIRWAYS_DB.MARTS.FCT_REVIEW_ENRICHED e
  JOIN BRITISH_AIRWAYS_DB.MARTS.DIM_LOCATION l ON e.TRANSIT_LOCATION_ID = l.LOCATION_ID
WHERE
  l.airport <> 'Unknown'
  AND e.SEAT_TYPE = 'Economy Class'
GROUP BY
  l.AIRPORT,
  e.TRANSIT_LOCATION_ID,
  l.CITY
ORDER BY
  1 DESC
LIMIT
  5