SELECT
  CASE
    WHEN TYPE_OF_TRAVELLER IS NULL THEN 'Unknown'
    ELSE TYPE_OF_TRAVELLER
  END AS TYPE,
  AVG(AVERAGE_RATING) AS average_rating,
  COUNT(*) AS review_count
FROM
  BRITISH_AIRWAYS_DB.MARTS.FCT_REVIEW_ENRICHED
GROUP BY
  CASE
    WHEN TYPE_OF_TRAVELLER IS NULL THEN 'Unknown'
    ELSE TYPE_OF_TRAVELLER
  END;