SELECT
  CASE
    WHEN VERIFIED = 'True' THEN 'Verified'
    ELSE 'Unverified'
  END AS VERIFIED,
  COUNT(*) AS count,
  ROUND(COUNT(*) / SUM(COUNT(*)) OVER (), 4) AS percentage
FROM
  BRITISH_AIRWAYS_DB.MARTS.FCT_REVIEW_ENRICHED
GROUP BY
  VERIFIED
ORDER BY
  VERIFIED;